repos:
-   repo: https://github.com/ambv/black
    rev: 21.5b1
    hooks:
    - id: black
      language_version: python3.10.5
      stages: [commit]

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      stages: [commit]

-   repo: local
    hooks:
      - id: requirements
        name: requirements
        entry: zsh -c 'pip freeze > requirements.txt'
        language: system
        pass_filenames: false
        stages: [commit]

-   repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.0
    hooks:
    -   id: absolufy-imports
        files: ^src/saas_metrics/

-   repo: https://github.com/econchick/interrogate
    rev: 1.4.0
    hooks:
      - id: interrogate
        args: [-vv]

# -   repo: https://github.com/PyCQA/isort
#     rev: 5.8.0
#     hooks:
#     -   id: isort